### ISSUE TITLE
Key error: user

### ISSUE THREAD

**Issue by DR0LLdr0id** [instabot-py/instabot.py#1022]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
windows 10

## Python Version?
3

## Description

everything was working fine last night, but this morning, as soon as i start it up, this error pops up and then it crashes
 

``` 
Traceback (most recent call last):
  File "C:\Users\Nemesis\Desktop\instabot.py-master\example.py", line 43, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Nemesis\Desktop\instabot.py-master\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\Users\Nemesis\Desktop\instabot.py-master\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Nemesis\Desktop\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'
```

**Comment by juanrojasm** [comment]
14.03.2018_10:54 Instabot v1.2.0 started at 14.03.2018 10:54:

14.03.2018_10:54 Trying to login as xxx...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/gouppers/123/src/instabot.py", line 231, in __init__
    self.login()
  File "/home/gouppers/123/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/gouppers/123/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

I have not been able to do it for 24 hours

**Comment by gersanchez** [comment]
The same for me!! 

Traceback (most recent call last):
  File "/home/ubuntu/workspace/example.py", line 52, in <module>
    unfollow_whitelist=['actriz.anaiurrego','tatiborrero','dianamor256','goodchicken26','danir_104','valecanizales','voltarock.cali', 'kmilsan92','palabradura','caroriverac1','minti_accesorios','santiago_bernalc','andresbernal12','jazminaltamar','falfada','loresilva','matgarcia91','ankgard','8a_carolina','tamy.13','gloriafigueroao','libellulaviajera','hannahmontanabananaindiana','bayrongomez','maria.sanchez.isaza','juancamilotg','jonazeto','ariasbolivarkl','karolaya29','shhhirleeey_','germanps90','christ_salazar','valentina.mendez19','diegonavarrete25','msdelvasto','jormora0327','xieloskydive','sanchezabril03','gr.rod','dianareinosa','falfada','nico2005lost','lvmc','sebascortes7','pawruizgo','pau_guti','yacambielnombre','juanpborrero','glory180','dianaquintanach','smlopez09','oscargarcia_voz'])
  File "/home/ubuntu/workspace/src/instabot.py", line 231, in __init__
    self.login()
  File "/home/ubuntu/workspace/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/ubuntu/workspace/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

**Comment by abdulsamad234** [comment]
Same here

**Comment by juanrojasm** [comment]
we must modify the userinfo and user_info files in / src
for these

# **src/userinfo**

#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json
import requests

class UserInfo:
'''
This class try to take some user info (following, followers, etc.)
'''
user_agent = ("Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 "
"(KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36")
url_user_info = "https://www.instagram.com/%..."
url_list = {
"ink361": {
"main": "http://ink361.com/",
"user": "http://ink361.com/app/users/%s",
"search_name": "https://data.ink361.com/v1/...",
"search_id": "https://data.ink361.com/v1/...",
"followers": "https://data.ink361.com/v1/...",
"following": "https://data.ink361.com/v1/...",
"stat": "http://ink361.com/app/users..."
}
}

def __init__(self, info_aggregator="ink361"):
self.i_a = info_aggregator
self.hello()

def hello(self):
self.s = requests.Session()
self.s.headers.update({'User-Agent': self.user_agent})
main = self.s.get(self.url_list[self.i_a]["main"])
if main.status_code == 200:
return True
return False

def get_user_id_by_login(self, user_name):
url_info = self.url_user_info % (user_name)
info = self.s.get(url_info)
all_data = json.loads(info.text)
id_user = all_data['graphql']['user']['id']
return id_user

def search_user(self, user_id=None, user_name=None):
'''
Search user_id or user_name, if you don't have it.
'''
self.user_id = user_id or False
self.user_name = user_name or False

if not self.user_id and not self.user_name:
# you have nothing
return False
elif self.user_id:
# you have just id
search_url = self.url_list[self.i_a]["search_id"] % self.user_id
elif self.user_name:
# you have just name
search_url = self.url_list[self.i_a][
"search_name"] % self.user_name
else:
# you have id and name
return True

search = self.s.get(search_url)

if search.status_code == 200:
r = json.loads(search.text)
if self.user_id:
# you have just id
self.user_name = r["data"]["username"]
else:
for u in r["data"]:
if u["username"] == self.user_name:
t = u["id"].split("-")
self.user_id = t[1]
# you have just name
return True
return False

def get_followers(self, limit=-1):
self.followers = None
self.followers = []
if self.user_id:
next_url = self.url_list[self.i_a]["followers"] % self.user_id
while True:
followers = self.s.get(next_url)
r = json.loads(followers.text)
for u in r["data"]:
if limit > 0 or limit < 0:
self.followers.append({
"username": u["username"],
#"profile_picture": u["profile_picture"],
"id": u["id"].split("-")[1],
#"full_name": u["full_name"]
})
limit -= 1
else:
return True
if r["pagination"]["next_url"]:
# have more data
next_url = r["pagination"]["next_url"]
else:
# end of data
return True
return False

def get_following(self, limit=-1):
self.following = None
self.following = []
if self.user_id:
next_url = self.url_list[self.i_a]["following"] % self.user_id
while True:
following = self.s.get(next_url)
r = json.loads(following.text)
for u in r["data"]:
if limit > 0 or limit < 0:
self.following.append({
"username": u["username"],
#"profile_picture": u["profile_picture"],
"id": u["id"].split("-")[1],
#"full_name": u["full_name"]
})
limit -= 1
else:
return True
if r["pagination"]["next_url"]:
# have more data
next_url = r["pagination"]["next_url"]
else:
# end of data
return True
return False

def get_stat(self, limit):
# todo
return False

'''
# example
ui = UserInfo()
# search by user_name:
ui.search_user(user_name="danbilzerian")
# or if you know user_id ui.search_user(user_id="50417061")
print(ui.user_name)
print(ui.user_id)

# get following list with no limit
ui.get_following()
print(ui.following)

# get followers list with limit 10
ui.get_followers(limit=10)
print(ui.followers)
'''

# **user_info**

#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
import json
import random
import time

def get_user_info(self, username):
if self.login_status:
now_time = datetime.datetime.now()
log_string = "%s : Get user info \n%s" % (
self.user_login, now_time.strftime("%d.%m.%Y %H:%M"))
self.write_log(log_string)
if self.login_status == 1:
url = 'https://www.instagram.com/%... % (username)
try:
r = self.s.get(url)

user_info = json.loads(r.text)

log_string = "Checking user info.."
self.write_log(log_string)

follows = user_info['graphql']['user']['edge_follow']['count']
follower = user_info['graphql']['user']['edge_followed_by']['count']
if self.is_self_checking is not False:
self.self_following = follows
self.self_follower = follower
self.is_self_checking = False
self.is_checked = True
return 0
media = user_info['graphql']['user']['edge_owner_to_timeline_media']['count']
follow_viewer = user_info['graphql']['user']['follows_viewer']
followed_by_viewer = user_info['graphql']['user']['followed_by_viewer']
requested_by_viewer = user_info['graphql']['user'][
'requested_by_viewer']
has_requested_viewer = user_info['graphql']['user'][
'has_requested_viewer']
log_string = "Follower : %i" % (follower)
self.write_log(log_string)
log_string = "Following : %s" % (follows)
self.write_log(log_string)
log_string = "Media : %i" % (media)
self.write_log(log_string)

if follows == 0 or follower / follows > 2:
self.is_selebgram = True
self.is_fake_account = False
print(' >>>This is probably Selebgram account')
elif follower == 0 or follows / follower > 2:
self.is_fake_account = True
self.is_selebgram = False
print(' >>>This is probably Fake account')
else:
self.is_selebgram = False
self.is_fake_account = False
print(' >>>This is a normal account')

if media > 0 and follows / media < 10 and follower / media < 10:
self.is_active_user = True
print(' >>>This user is active')
else:
self.is_active_user = False
print(' >>>This user is passive')

if follow_viewer or has_requested_viewer:
self.is_follower = True
print(" >>>This account is following you")
else:
self.is_follower = False
print(' >>>This account is NOT following you')

if followed_by_viewer or requested_by_viewer:
self.is_following = True
print(' >>>You are following this account')
else:
self.is_following = False
print(' >>>You are NOT following this account')
self.is_checked = True
except:
self.media_on_feed = []
self.write_log("Except on get_info!")
time.sleep(20)
return 0
else:
return 0

**Comment by lasododo** [comment]
after I edited both files I got this error : 

Traceback (most recent call last):
  File "example.py", line 56, in <module>
    unfollow_whitelist=['example1', 'example2']
  File "C:\Users\StyleZ\PycharmProjects\instabot.py-master\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\Users\StyleZ\PycharmProjects\instabot.py-master\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\StyleZ\PycharmProjects\instabot.py-master\src\userinfo.py", line 39, in get_user_id_by_login
    url_info = self.url_user_info % (user_name)
ValueError: unsupported format character '.' (0x2e) at index 28

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
